version: '3'

services:
  web:
    container_name: django_app
    build: .
    command: python applications/vegas/manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/code
    ports:
    - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:11