version: "3"
services:
  os:
    image: "ubuntu:focal"
    container_name: "antimainstream53/ubuntucore"
    ports:
      - "8080:8080"
  db:
    image: "postgres:11"
    container_name: "myDB"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"


