version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "myDB"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"


